apiVersion: v1
kind: Service
metadata:
  name:  {{ .Values.fullName}}-load-balancer
  namespace: platform
  labels:
    app: {{ .Values.selectorLabel }}
spec:
  type: LoadBalancer
  ports:
    - port: {{ .Values.service.tendermintPort }}
      targetPort: {{ .Values.service.tendermintPort }}
      name: tendermint
    - port: {{ .Values.service.p2pPort }}
      targetPort: {{ .Values.service.p2pPort }}
      name: p2p
    - port: {{ .Values.service.rpcPort }}
      targetPort: {{ .Values.service.rpcPort }}
      name: rpc
  selector:
    app: {{ .Values.selectorLabel }}


