apiVersion: v1
kind: Service
metadata:
  name:  {{ .Values.fullName}}-node-port
  namespace: platform
  labels:
    app: {{ .Values.selectorLabel }}
spec:
  type: NodePort
  ports:
    - port: {{ .Values.service.blockchainApiPort }}
      targetPort: {{ .Values.service.blockchainApiPort }}
      name: api
      nodePort: 31317
  selector:
    app: {{ .Values.selectorLabel }}


