replicasCount: 1
fullName: "solechain-spn"
selectorLabel: "solechain-spn"

domain: "spn.solenopsys.org"

service:
  rpcPort: 26657
  tendermintPort: 26660
  p2pPort: 26656
  blockchainApiPort: 1317

storage:
  volumeName: spn-volume
  volumeClimeName: spn-pvc
  storageSize: 1Gi
  accessModes: "ReadWriteOnce"
  hostPath: "/opt/spn-volume"
  storageClass: "local-path"

containers:
  spn_node:
    name: spn
    image: registry.solenopsys.org/solechain-spn:latest
    pullPolicy: IfNotPresent

